comment: false
coverage:
  status:
    patch:
      default:
        target: '10'
    project:
      default:
        target: '10'
fixes:
  - "*active_directory/datadog_checks/active_directory/::active_directory/"
  - "*active_directory/tests/::active_directory/"